### ISSUE TITLE
Not Found: es2017-lambda-boilerplate@latest

### ISSUE THREAD

**Issue by XBeg9** [irvinlim/es2017-lambda-boilerplate#28]
Could you please fix this?

```bash
npm install --save-dev es2017-lambda-boilerplate
npm ERR! code E404
npm ERR! 404 Not Found: es2017-lambda-boilerplate@latest`

**Comment by XBeg9** [comment]
Installing from github (master)
`"es2017-lambda-boilerplate": "github:irvinlim/es2017-lambda-boilerplate"` throws error:  `Module build failed: Error: Couldn't find preset "es2017-lambda-boilerplate"`

Any ideas what am I doing wrong here? Thanks

**Comment by XBeg9** [comment]
Nevermind, just saw :) it's boilerplate. My bad. Sorry

**Comment by irvinlim** [comment]
No problem, glad to hear you figured it out! :)
